using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(BoxCollider))]

public class RepeatBackground : MonoBehaviour
{
    private Vector3 startPos;//Posici칩n inicial del fondo

    private float repeatWidth;//Anchura del fondo (de su collider en realidad)
    // Start is called before the first frame update
    void Start()
    {
        startPos = transform.position;
        
        //Obtenemos el tama침o del collider en x, que es el eje que interesa, y lo dividimos por 2 para obtener el valor
        //exacto en el que se habr치 alcanzado punto en que la imagen de fondo debe recolocarse
        repeatWidth = GetComponent<BoxCollider>().size.x / 2;
    }

    // Update is called once per frame
    void Update()
    {
        //Si se alcanza el punto de repetici칩n recolocamos la imagen de fondo
        if (startPos.x - transform.position.x > repeatWidth)
            transform.position = startPos;
    }
}
